project:
  type: website

website:
  title: "Finist'R 2024"
  navbar:
    left:
      - icon: github
        href: https://github.com/StateOfTheR/finistR2024
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
    right:
      - text: Algorithme
        menu:
        - text: Initiation Ã  `Nimble`
          href: 01_nimble.qmd
        - text: C++ depuis Python
          href: c_python.qmd
      - text: Themes to be developped
        menu:
        - text: List to discussed
          href: theme.qmd
        aria-label: GitHub
format:
  html:
    theme: flatly
    highlight: tango
    toc: true
    
